{% set version = "2.0.5" %}

package:
  name: qtpy-uic
  version: {{ version }}

source:
  url: https://github.com/hmaarrfk/qtpy-tools/archive/{{ version }}.tar.gz
  fn: qtpy-tools-{{ version }}.tar.gz
  sha256: eb6f48fef5825887a158521d7e72339b97caeddb5afa9035e26b028c59f831ab

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv --disable-pip-version-check
  noarch: python
  entry_points:
    - qtpy-uic = qtpyuic:main

requirements:
  host:
    - python >=3
    - pip
    - setuptools
  run:
    - python >=3

test:
  imports:
    - qtpyuic
  commands:
    - qtpy-uic --help

about:
  home: https://github.com/hmaarrfk/qtpy-tools/
  license: GPLv2
  license_family: GPL
  license_file: LICENSE-uic
  summary: qtpy ui compiler

extra:
  recipe-maintainers:
    - hmaarrfk
