travis:
  secure:
    BINSTAR_TOKEN: NUF0OUjG6v8oMvKh0Fz+BcS3WbgS3rQGYlnH9folQpYgpXGj/7kzuftmVuucuvAMvmwMiGcTT0Oc1N/8Xjp9oeL1XU4r5Blk0aaqfvnDT8Wn1NhTQ7is8TSO2se09fDMIyJQflItJS4oOtmM50XhDfiG854869Uqb9sB/JWmxQnswHRKppga1vUpz3a6+PszOsEHx22KtcWhXzaH8oQkkgRRlgHBsU15L6u87vP/0uWrmCVpnaANJVParp4fiCBVESBbS5b9zhHxghiFKNIjMMLhPhj2P1Pd/9nRgyi7zulbjJop27K8r1ZNUP1fYstXlzaZsLHRSLAGyZtCHoXfGHOUQ9/8dSJNUWbbuiYn7eZItRYY8mo1hp1QRfY1S5U6zLeU7Mex+pn5v92e8zV6scJWNzF0jdI6WbyNZwCVVP0hp9wRhCJiZk3PyrcukKgeLxDVakzT7Yl6/oSsVZENzEneH4zdTzLhwOtMCZDQIyYBibYojq14tD+PHYpGHw/vYE1eiglr64rbBRov7x99rBIs2G/r+bspBkZibBKO+AHVSD4zo9WuWlG4ndHOvMFjGXa1hFA1wl0dD4wucK+NK8vPi4uJUDHPY6a2GqsnjWNjj8DksJvPdhxMZd+avdjMmzRoIkk6OAXROXhHrwwJ0NCSgmOFa9hGtqUqSYWWptk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
